name: Build GlobalSort GUI for Windows, Linux, and macOS

on:
  workflow_dispatch:  # This allows manual trigger from GitHub Actions UI

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build GlobalSort Application for Windows
      run: |
        pyinstaller main.spec

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build-artifacts
        path: ./dist/*

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build GlobalSort Application for Linux
      run: |
        pyinstaller main_macos_linux.spec

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-build-artifacts
        path: ./dist/*

  build_macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build GlobalSort Application for macOS ARM
      run: |
        arch -arm64 pyinstaller main_macos_linux.spec  # Build for ARM

    - name: Archive ARM build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-arm-build-artifacts
        path: ./dist/*

    - name: Build GlobalSort Application for macOS Intel
      run: |
        arch -x86_64 pyinstaller main_macos_linux.spec  # Build for Intel

    - name: Archive Intel build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-intel-build-artifacts
        path: ./dist/*

  create_release:
    runs-on: ubuntu-latest
    needs: [build_windows, build_linux, build_macos]

    steps:
    - name: Download Windows build artifacts
      uses: actions/download-artifact@v2
      with:
        name: windows-build-artifacts
        path: ./artifacts/windows

    - name: Download Linux build artifacts
      uses: actions/download-artifact@v2
      with:
        name: linux-build-artifacts
        path: ./artifacts/linux

    - name: Download macOS ARM build artifacts
      uses: actions/download-artifact@v2
      with:
        name: macos-arm-build-artifacts
        path: ./artifacts/macos/arm

    - name: Download macOS Intel build artifacts
      uses: actions/download-artifact@v2
      with:
        name: macos-intel-build-artifacts
        path: ./artifacts/macos/intel

    - name: List Windows Artifact Directory
      run: ls -R ./artifacts/windows

    - name: List Linux Artifact Directory
      run: ls -R ./artifacts/linux

    - name: List macOS ARM Artifact Directory
      run: ls -R ./artifacts/macos/arm

    - name: List macOS Intel Artifact Directory
      run: ls -R ./artifacts/macos/intel

    - name: Rename Windows Artifact
      run: |
        mv "./artifacts/windows/GlobalSort GUI.exe" "./artifacts/windows/GlobalSort_GUI_Windows_${{ github.run_number }}.exe"

    - name: Rename Linux Artifact
      run: |
        mv "./artifacts/linux/GlobalSort GUI" "./artifacts/linux/GlobalSort_GUI_Linux_${{ github.run_number }}"

    - name: Rename macOS ARM Artifact
      run: |
        mv "./artifacts/macos/arm/GlobalSort GUI" "./artifacts/macos/GlobalSort_GUI_macOS_ARM_${{ github.run_number }}"

    - name: Rename macOS Intel Artifact
      run: |
        mv "./artifacts/macos/intel/GlobalSort GUI" "./artifacts/macos/GlobalSort_GUI_macOS_Intel_${{ github.run_number }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: GlobalSort_${{ github.run_number }}
        release_name: GlobalSort_Release.${{ github.run_number }}
        body: |
          New release of GlobalSort GUI automatically built by GitHub Actions for Windows, Linux, and macOS.
        draft: true
        prerelease: true

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./artifacts/windows/GlobalSort_GUI_Windows_${{ github.run_number }}.exe"
        asset_name: GlobalSort_GUI_Windows_${{ github.run_number }}.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./artifacts/linux/GlobalSort_GUI_Linux_${{ github.run_number }}"
        asset_name: GlobalSort_GUI_Linux_${{ github.run_number }}"
        asset_content_type: application/octet-stream

    - name: Upload macOS ARM Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./artifacts/macos/GlobalSort_GUI_macOS_ARM_${{ github.run_number }}"
        asset_name: GlobalSort_GUI_macOS_ARM_${{ github.run_number }}"
        asset_content_type: application/octet-stream

    - name: Upload macOS Intel Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./artifacts/macos/GlobalSort_GUI_macOS_Intel_${{ github.run_number }}"
        asset_name: GlobalSort_GUI_macOS_Intel_${{ github.run_number }}"
        asset_content_type: application/octet-stream
